package com.bigdata.rpc.webservice.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-04-25T12:55:10.900+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://service.original.webservice.bigdata.com/", name = "BookServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface BookServiceImpl {

    @WebMethod
    @Action(input = "http://service.original.webservice.bigdata.com/BookServiceImpl/getAllRequest", output = "http://service.original.webservice.bigdata.com/BookServiceImpl/getAllResponse")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.original.webservice.bigdata.com/", className = "com.bigdata.webservice.cxf.client.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.original.webservice.bigdata.com/", className = "com.bigdata.webservice.cxf.client.GetAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Book> getAll()
;

    @WebMethod
    @Action(input = "http://service.original.webservice.bigdata.com/BookServiceImpl/getByIdRequest", output = "http://service.original.webservice.bigdata.com/BookServiceImpl/getByIdResponse")
    @RequestWrapper(localName = "getById", targetNamespace = "http://service.original.webservice.bigdata.com/", className = "com.bigdata.webservice.cxf.client.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://service.original.webservice.bigdata.com/", className = "com.bigdata.webservice.cxf.client.GetByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Book getById(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
