
package com.bigdata.rpc.webservice.cxf.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-04-25T12:55:10.849+08:00
 * Generated source version: 3.3.6
 *
 */
public final class BookServiceImpl_BookServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.original.webservice.bigdata.com/", "BookServiceImplService");

    private BookServiceImpl_BookServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BookServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BookServiceImplService ss = new BookServiceImplService(wsdlURL, SERVICE_NAME);
        BookServiceImpl port = ss.getBookServiceImplPort();

        {
        System.out.println("Invoking getAll...");
        java.util.List<Book> _getAll__return = port.getAll();
        System.out.println("getAll.result=" + _getAll__return);


        }
        {
        System.out.println("Invoking getById...");
        int _getById_arg0 = 0;
        Book _getById__return = port.getById(_getById_arg0);
        System.out.println("getById.result=" + _getById__return);


        }

        System.exit(0);
    }

}
