// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package com.bigdata.rpc.grpc.api.greeting;

public interface GreetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bigdata.rpc.grpc.api.GreetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
