
package com.bigdata.rpc.webservice.cxf.server;

import com.bigdata.rpc.webservice.cxf.impl.BookServiceImplPortImpl;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-04-25T12:55:12.424+08:00
 * Generated source version: 3.3.6
 *
 */

public class BookServiceImpl_BookServiceImplPort_Server{

    protected BookServiceImpl_BookServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BookServiceImplPortImpl();
        String address = "http://127.0.0.1:8080/book/ws";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new BookServiceImpl_BookServiceImplPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
