
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bigdata.rpc.webservice.cxf.impl;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-04-25T12:55:13.998+08:00
 * Generated source version: 3.3.6
 *
 */

@javax.jws.WebService(
                      serviceName = "BookServiceImplService",
                      portName = "BookServiceImplPort",
                      targetNamespace = "http://service.original.webservice.bigdata.com/",
//                      wsdlLocation = "http://127.0.0.1:8080/book/ws?wsdl",
                      endpointInterface = "com.bigdata.rpc.webservice.cxf.impl.BookServiceImpl")

public class BookServiceImplPortImpl implements BookServiceImpl {

    private static final Logger LOG = Logger.getLogger(BookServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bigdata.webservice.cxf.impl.BookServiceImpl#getAll()*
     */
    public java.util.List<Book> getAll() {
        LOG.info("Executing operation getAll");
        try {
            java.util.List<Book> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.bigdata.webservice.cxf.impl.BookServiceImpl#getById(int arg0)*
     */
    public Book getById(int arg0) {
        LOG.info("Executing operation getById");
        System.out.println(arg0);
        try {
            Book _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
