
package com.bigdata.rpc.webservice.wsimport.refer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookServiceImpl", targetNamespace = "http://service.original.webservice.bigdata.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.bigdata.webservice.wsimport.refer.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://service.original.webservice.bigdata.com/", className = "com.bigdata.webservice.wsimport.refer.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://service.original.webservice.bigdata.com/", className = "com.bigdata.webservice.wsimport.refer.GetByIdResponse")
    @Action(input = "http://service.original.webservice.bigdata.com/BookServiceImpl/getByIdRequest", output = "http://service.original.webservice.bigdata.com/BookServiceImpl/getByIdResponse")
    public Book getById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.bigdata.webservice.wsimport.refer.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.original.webservice.bigdata.com/", className = "com.bigdata.webservice.wsimport.refer.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.original.webservice.bigdata.com/", className = "com.bigdata.webservice.wsimport.refer.GetAllResponse")
    @Action(input = "http://service.original.webservice.bigdata.com/BookServiceImpl/getAllRequest", output = "http://service.original.webservice.bigdata.com/BookServiceImpl/getAllResponse")
    public List<Book> getAll();

}
